# Generated by Django 4.1 on 2022-08-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="title", field=models.CharField(max_length=120),
        ),
    ]
