# Generated by Django 4.1 on 2022-08-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
